# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Custom rules for this project
Layout/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 10
Metrics/ClassLength:
  Max: 100
Metrics/BlockLength:
  Max: 25
Style/StringLiterals:
  EnforcedStyle: single_quotes

